// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace banqueFunTest
{

    [TestFixture]
    public class ScenarioprincipalChromeTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            //driver = new FirefoxDriver();
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void scenarioprincipal()
        {
            // Test name: Scénario principal
            // Step # | name | target | value
            // 1 | open | / | 
            driver.Navigate().GoToUrl("http://localhost/");
            // 2 | setWindowSize | 1212x716 | 
            //driver.Manage().Window.Size = new System.Drawing.Size(1212, 716);
            // 3 | verifyText | css=h2 | Bienvenue sur votre Banque en ligne !!!
            Assert.That(driver.FindElement(By.CssSelector("h2")).Text, Is.EqualTo("Bienvenue sur votre Banque en ligne !!!"));
            // 4 | click | linkText=Accès client | 
            driver.FindElement(By.LinkText("Accès client")).Click();
            // 5 | verifyElementPresent | id=authIdentifiant | 
            var elements = driver.FindElements(By.Id("authIdentifiant"));
            Assert.True(elements.Count > 0);
            // 6 | verifyElementPresent | id=authMotdepasse | 
            elements = driver.FindElements(By.Id("authMotdepasse"));
            Assert.True(elements.Count > 0);
            // 7 | verifyElementPresent | css=.btn | 
            elements = driver.FindElements(By.CssSelector(".btn"));
            Assert.True(elements.Count > 0);
            // 8 | click | linkText=Nous Contacter | 
            driver.FindElement(By.LinkText("Nous Contacter")).Click();
            // 9 | verifyText | css=h3 | Nous contacter
            Assert.That(driver.FindElement(By.CssSelector("h3")).Text, Is.EqualTo("Nous contacter"));
        }
    }

}